-- Problem registry, first pass (2026-09-20).
-- Method: clusters found by tag and keyword queries over the 192 analysed items, then each claim checked against upstream
-- sezanzeb/input-remapper at commit cb8f5fd (2026-09-14) by reading the docs and code. Everything here is conf:inferred until a maintainer confirms.
-- Only verified problems are registered; items that could not be checked (GUI behaviour, Restore Defaults flow) are deliberately left out.
INSERT INTO problem VALUES ('uinput-module-not-loaded', 'Injection fails when the uinput kernel module is not loaded', 'Injection fails with "could not open uinput device" when the uinput kernel module is not loaded (reported on Arch and postmarketOS; fixed by running modprobe uinput, sometimes needed after a kernel upgrade). Verified at upstream cb8f5fd: no modprobe, modules-load.d file or troubleshooting note exists in the docs, install scripts, packaging or data/. Candidate PR: ship a modules-load.d entry for uinput with the package and add a troubleshooting note to the README. Not yet tested on a distribution.', 'open');
INSERT INTO problem VALUES ('no-non-systemd-init-scripts', 'Only a systemd unit ships; no OpenRC, runit or sysv scripts', 'Only data/input-remapper.service ships, so the daemon cannot be autostarted on OpenRC, runit or sysv systems (Gentoo, Artix, Alpine, postmarketOS). In #15 the maintainer asked for a PR and community members posted working OpenRC and runit scripts in the thread. Verified at upstream cb8f5fd: no OpenRC, runit or sysv files in the repository. Candidate PR: contributed init scripts plus a README section; needs someone who can test on those systems.', 'open');
INSERT INTO problem VALUES ('per-app-switching-wayland', 'Presets that follow the focused application are impossible on Wayland, and the docs do not say so', 'Users keep asking for presets that switch by focused application or window (seven items over five years). The maintainer answers each time that Wayland hides window focus, so it cannot work on every desktop. Verified at upstream cb8f5fd: README, usage.md and examples.md do not state this limit or the workaround (input-remapper-control bound to a desktop shortcut, or an X11 window-watcher script). Candidate PR: an FAQ entry. The feature itself is not being asked of the maintainer.', 'open');
INSERT INTO problem VALUES ('requested-features-still-missing', 'Requested features still missing upstream (each a separate PR)', 'Open requests verified absent at upstream cb8f5fd: a text() macro (#173), an LED macro (#160; a contributor started a branch), udev-based device classification (#192), search or filter of the mapping list (#207), desktop notifications when a device is mapped (#116). These are separate PRs, grouped only because each is a small missing feature.', 'open');
INSERT INTO problem VALUES ('already-fixed-or-documented-upstream', 'Asks that upstream already meets', 'Verified at upstream cb8f5fd (2026-09-14): #66 a uinput device name longer than 80 characters is truncated (injector.py: name[:80]); #11 and #81 uninstalling is documented (README: sudo python3 -m install.uninstall); #269 python3-devel is listed in the README dependencies. No PR needed; their pr_potential is re-tagged resolved.', 'closed');
INSERT INTO problem_item VALUES ('uinput-module-not-loaded', 29), ('uinput-module-not-loaded', 122), ('uinput-module-not-loaded', 256);
INSERT INTO problem_item VALUES ('no-non-systemd-init-scripts', 15), ('no-non-systemd-init-scripts', 122);
INSERT INTO problem_item VALUES ('per-app-switching-wayland', 32), ('per-app-switching-wayland', 50), ('per-app-switching-wayland', 56), ('per-app-switching-wayland', 146), ('per-app-switching-wayland', 196), ('per-app-switching-wayland', 203), ('per-app-switching-wayland', 252);
INSERT INTO problem_item VALUES ('requested-features-still-missing', 116), ('requested-features-still-missing', 160), ('requested-features-still-missing', 173), ('requested-features-still-missing', 192), ('requested-features-still-missing', 207);
INSERT INTO problem_item VALUES ('already-fixed-or-documented-upstream', 11), ('already-fixed-or-documented-upstream', 66), ('already-fixed-or-documented-upstream', 81), ('already-fixed-or-documented-upstream', 269);
UPDATE tag SET value = 'resolved' WHERE facet = 'pr_potential' AND item_n IN (11, 66, 81, 269) AND value IN ('code-fix', 'docs-fix');
